name: Github actions main branch

run-name: "${{ github.actor }} performed ${{ github.event_name }} on ${{ github.head_ref || github.ref_name }}"

on:
    push:
        branches: 
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup NodeJs
              uses: actions/setup-node@v4
              with: 
                node-version: 20
            - name: Install dependencies
              run:  npm install

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup NodeJs
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Install dependencies
              run: npm install
            
            - name: Run tests
              run: npm run test
    
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setuo Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Install deps
              run: npm install
            
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-central-1

            - name: Synth CDK stack
              run: |
                npx cdk synth > cdk_output.yaml
                echo "Synth success"


            - name: Deploy CDK Stack
              run: |
                npx cdk deploy
                echo "Deploy success"